In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_excel(r'C:\Users\dawns\Desktop\Master thesis\data\Dataset_L1 learner_clean.xlsx',index_col=None, header=0)

In [3]:
train_data

,id,student_id,title,content,create_time,content_length,gradeid,classid
0,f207dc5aa89511eaa65b54e1ad63dcde,5139,不容易的林楠,林楠是一个从农村转到这所学校的，家庭条件很不好。刚去面试的时候，校长对林楠的印象很不好，林楠...,2019-07-01,1088,G05,51
1,f20a75c4a89511eaa65b54e1ad63dcde,2106,我是一只小兔子,我是一只小兔子，我的伙伴说当一只小兔子一点也不好，因为一不小心就会被大灰狼吃掉的，你觉得得当...,2019-07-01,762,G02,21
2,f20d440fa89511eaa65b54e1ad63dcde,2311,我是一只老虎,当一只老虎好不好，同学们都说当一只小老虎不好。\n你每天在森林里找食物吃，可别的小动物害怕老...,2019-07-01,503,G02,23
3,f20faf5ba89511eaa65b54e1ad63dcde,2232,我是一只小猴子,在森林里，我的伙伴又一次是爬树冠军，但是他们觉得比赛很累。\n我也参加了一个爬树比赛，他们都...,2019-07-01,572,G02,22
4,f21246a9a89511eaa65b54e1ad63dcde,3338,第五十一变的有趣经历,我有七十二变的本领。哈哈，你们肯定很羡慕我吧。有一天，我正在一片森林里练习我的七十二变，可是...,2019-07-01,958,G03,33
...,...,...,...,...,...,...,...,...
8313,26d44fb3a94711eaa65b54e1ad63dcde,1247,小鸭和小鸡,有一天早晨，小鸭和小鸡去郊外游玩，它们来到小河边小鸡过不去小鸭帖这小鸡走，小鸭走这走这小鸭掉...,2009-12-23,106,G01,12
8314,26d538cfa94711eaa65b54e1ad63dcde,1248,救小鸡,早晨天气很好小鸡和小鸭玩玩呀玩呀扑通一下小鸡水里\n小鸭飞快跳进水里一下就把小鸡救出来了后天...,2009-12-23,92,G01,12
8315,26d63508a94711eaa65b54e1ad63dcde,1249,小鸡救小鸭,星期六，小鸡和小鸭在河边玩小鸡说我想去河边看看小鸭说你到我，的背上我带你去那边看看，突然小...,2009-12-23,100,G01,12
8316,26d71675a94711eaa65b54e1ad63dcde,1250,小鸡救小鸭,中午小鸡和小鸭去玩前面有一个小河， \n小鸭说你上我背上来吧。小鸭背着小鸡过河，\n他们继...,2009-12-23,128,G01,12
8317,26d7f495a94711eaa65b54e1ad63dcde,1251,救小鸭,有一天，小鸡和小鸭他们出去玩。\n他们玩得很开心不一会小鸡要过河。\n小鸭就托这小鸡过河了小...,2009-12-23,101,G01,12

In [8]:

train_data.sample(n=3668)

,id,student_id,title,content,create_time,content_length,gradeid,classid
1178,0dba4167a89611eaa65b54e1ad63dcde,3328,想要自由的小猴子,小猴子离开动物园之前，还吃了点东西，小猴子吃完，就赶紧往旁边的树林跑去。\n小猴子跑啊跑啊，...,2018-12-21,608,G03,33
5308,09b6494fa93811eaa65b54e1ad63dcde,2120,妈妈的爱,在一个秋天的早晨，微风会轻轻地吹着，好像在悠闲地走着，每一天都天气晴朗，阳光明媚，天上飘着几...,2015-12-22,836,G02,21
1553,112e5c33a89611eaa65b54e1ad63dcde,1220,假如我是个布娃娃,假如我是个布娃娃，我是一个有生命力的布娃娃，我跟我的玩具朋友去探索辽阔的世界，也要...,2018-12-21,923,G01,12
300,f5255fe5a89511eaa65b54e1ad63dcde,3143,第五十一变的有趣经历,我拥有着一个超凡的本领——七十二变。没错，就是和孙悟空一样的七十二变。但是我一天只能变一次，...,2019-07-01,573,G03,31
6949,11882313a93f11eaa65b54e1ad63dcde,2207,秋天来到我身边。,秋天来了，秋天凉了，也没有人到花园、果园、田野里去玩了，秋姑姑悄悄来到我们身边。\n秋姑姑来...,2012-11-07,404,G02,22
...,...,...,...,...,...,...,...,...
6686,a99097a2a93c11eaa65b54e1ad63dcde,3441,地球人的信,美国莱州制作了一个非常精致又坚固的盒子，里面装着三千年后的信。\n一转眼，到了三千年后了，人...,2013-06-28,526,G03,34
2646,4a4df777a89b11eaa65b54e1ad63dcde,2120,小刺猬给小熊的称赞,小刺猬走出门外，看到了一只小熊正在学做板凳，看起来小熊做每个板凳的时候都很用心，小刺猬走到了...,2017-12-20,459,G02,21
2491,490bb85ca89b11eaa65b54e1ad63dcde,1138,过桥,在一个美里的森林里有，红红的花、绿绿的草、高高的树、还有一条小河，唱着歌流淌着，河对岸有一个...,2017-12-20,348,G01,11
6101,a623bec0a93c11eaa65b54e1ad63dcde,1136,聪明的小刺猬,在一片大森林里住着一只小刺猬，有一天，万里无云，春风拂面，小刺猬到苹果树下捡苹果吃，小刺猬一...,2013-06-28,310,G01,11
3078,4dcb1fe0a89b11eaa65b54e1ad63dcde,5241,地球上的最后一个人,地球上的最后一个人孤独的坐在房间里，这时，忽然响起了一阵敲门声，地球上的最后一个人说：“地球...,2017-12-20,678,G05,52

In [9]:
random= pd.DataFrame()
random = train_data.sample(n=3668)

In [10]:
random.to_excel(r'C:\Users\dawns\Desktop\Master thesis\data\L1_randomselect.xlsx')